excluded:
  - Carthage
  - Pods

opt_in_rules:
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma
  - force_unwrapping

force_unwrapping: error

identifier_name:
  min_length:
    error: 3
  excluded:
      - vm
      - id

disabled_rules:
  - identifier_name
  - nesting
  - function_parameter_count
  - trailing_whitespace
  - superfluous_disable_command
  - blanket_disable_command
  - legacy_random
  - unused_optional_binding

type_body_length:
  - 300 # warning
  - 500 # error

file_length:
  warning: 500
  error: 800

line_length:
  warning: 400
  error: 500
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true